trigger:
- master  # or your specific branch

variables:
  # Docker Hub credentials
  DOCKER_REGISTRY_SERVICE_CONNECTION: dockerhub
  IMAGE_NAME: sadiksa/dotnetdemonew
  DOCKERFILE_PATH: Dockerfile  # Path to your Dockerfile

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      name: buildernew

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(DOCKER_REGISTRY_SERVICE_CONNECTION)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: '$(DOCKERFILE_PATH)'
        tags: |
          latest
