apiVersion: v1
kind: Service
metadata:
  name: dotnet-demo
  namespace: devops
spec:
  selector:
    app: dotnet-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 
  type: NodePort